### ISSUE TITLE
simple workflow

### ISSUE THREAD

**Issue by avichazen** [avichazen/api-doc-example-obw#5]
![simple workflow](https://user-images.githubusercontent.com/70967800/100220832-8ca4c680-2f20-11eb-9f09-318b8abe76c8.png)

**Comment by lsnovich** [comment]
The issue with this diagram is
1 - the order burger should not be yes / no
2 there are too many choices in the "bun and patty type, condiments and toppings"
this needs to be singular actions / choices
consider changing want patty? to choose a patty type and make it an action ( you do not need to list the choices)

**Comment by lsnovich** [comment]
but this is SO much better than before

**Comment by avichazen** [comment]
Updated workflow
